name: Compliance Workflow

on: 
  schedule:
  - cron: '0 7 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: cd remote_write &&  go test --tags=compliance -run "TestRemoteWrite/prometheus/.+" -v ./ &&  go test --tags=compliance -run "TestRemoteWrite/otel/.+" -v ./